# -*- coding: utf-8 -*-
"""Occassion_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VEwNBlQ1zcoYmXaP8AaR7K26V4gIoTJe
"""


import tensorflow as tf
import cv2
import tensorflow
import os
from tensorflow.keras.models import load_model
import numpy as np

import cv2

import tensorflow as tf
import keras
from keras import Model
from keras.applications.resnet50 import ResNet50
from keras.preprocessing import image 
from keras.applications.resnet50 import preprocess_input, decode_predictions
from keras.layers import GlobalMaxPooling2D
import matplotlib.pyplot as plt


occ=load_model('Occasion/final_model_v2')
classes={'0':'ethnic','1':'cassual','2':'formal'}

def kunal(img):
  print(img)
  img=cv2.imread(img)
  plt.imshow(img)
  # plt.show()
  img=cv2.GaussianBlur(img,(3,3),9)
  x=cv2.resize(img,(224,224),interpolation=cv2.INTER_AREA)    
  x=x/255
  return classes[str(occ.predict_classes(np.asarray([x]))[0])]




  





